import { ChevronLeft, ChevronRight, Search } from 'lucide-react';
import type { BriefRule, RuleStatus } from '../types/review';
import { StatusBadge } from './StatusBadge';
export type StatusFilter = 'all' | RuleStatus;
const severity: Record<RuleStatus,number>={violation:0,warning:1,insufficient:2,passed:3};
export function sortRules<T extends BriefRule>(rules:T[]):T[]{return rules.map((rule,index)=>({rule,index})).sort((a,b)=>severity[a.rule.status]-severity[b.rule.status]||a.rule.number-b.rule.number||a.index-b.index).map(item=>item.rule);}
export function useRuleFilter(rules: BriefRule[], query: string, status: StatusFilter, page: number, pageSize=10){const filtered=sortRules(rules).filter(r=>(status==='all'||r.status===status)&&(`${r.number} ${r.title}`.toLowerCase().includes(query.toLowerCase())));const pages=Math.max(1,Math.ceil(filtered.length/pageSize));return {filtered,pages,items:filtered.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize)};}
export function RuleToolbar({query,onQuery,status,onStatus}:{query:string;onQuery:(v:string)=>void;status:StatusFilter;onStatus:(v:StatusFilter)=>void}){return <div className="rule-toolbar"><label className="search-box"><Search size={16}/><span className="sr-only">搜索规则</span><input value={query} onChange={e=>onQuery(e.target.value)} placeholder="搜索规则编号或内容"/></label><label><span className="sr-only">状态筛选</span><select value={status} onChange={e=>onStatus(e.target.value as StatusFilter)}><option value="all">全部状态</option><option value="violation">违规</option><option value="warning">预警</option><option value="insufficient">输入不足</option><option value="passed">通过</option></select></label></div>}
export function Pagination({page,pages,onPage}:{page:number;pages:number;onPage:(n:number)=>void}){return <div className="pagination"><button aria-label="上一页" disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></button><div className="page-numbers">{Array.from({length:pages},(_,index)=>index+1).map(value=><button key={value} className={value===page?'active':''} aria-label={`第 ${value} 页`} aria-current={value===page?'page':undefined} onClick={()=>onPage(value)}>{value}</button>)}</div><button aria-label="下一页" disabled={page>=pages} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></button></div>}
export function RuleRows({rules,onSelect,selected}:{rules:BriefRule[];onSelect?:(r:BriefRule)=>void;selected?:string}){return <div className="rule-rows">{rules.map(r=><button key={r.id} className={`rule-row ${selected===r.id?'selected':''}`} onClick={()=>onSelect?.(r)}><span className="rule-number">{String(r.number).padStart(2,'0')}</span><span className="rule-title">{r.title}</span><StatusBadge status={r.status}/></button>)}</div>}
