#!/usr/bin/env bash
# 所有服务脚本共用的唯一配置加载器。本文件只应被 source，不应单独执行。

if [[ -z "${APP_PROJECT_ROOT:-}" ]]; then
  APP_PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
  export APP_PROJECT_ROOT
fi

APP_CONFIG_FILE="${APP_CONFIG_FILE:-$APP_PROJECT_ROOT/config/runtime.env}"
export APP_CONFIG_FILE

if [[ ! -f "$APP_CONFIG_FILE" ]]; then
  echo "运行配置不存在: $APP_CONFIG_FILE" >&2
  echo "请先执行: bash $APP_PROJECT_ROOT/scripts/setup_runtime_config.sh" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$APP_CONFIG_FILE"
set +a

require_runtime_vars() {
  local name
  local missing=0
  for name in "$@"; do
    if [[ -z "${!name:-}" ]]; then
      echo "运行配置缺少必填项: $name" >&2
      missing=1
    fi
  done
  if [[ "$missing" -ne 0 ]]; then
    exit 1
  fi
}

runtime_bool_is_true() {
  case "$1" in
    1|[Tt][Rr][Uu][Ee]|[Yy][Ee][Ss]|[Oo][Nn]) return 0 ;;
    *) return 1 ;;
  esac
}

require_algorithm_runtime_vars() {
  require_runtime_vars POLICY_RULES_PATH ALGORITHM_MAX_SECTION_PAGES ALGORITHM_CANDIDATE_COUNT ALGORITHM_EVIDENCE_COUNT ALGORITHM_MINIMUM_SCORE ALGORITHM_USE_EMBEDDING ALGORITHM_USE_LLM_MATCHING ALGORITHM_STRICT_LLM ALGORITHM_ENABLE_LLM_CHECK ALGORITHM_LLM_REVIEW MATCHING_WORKERS SEMANTIC_WORKERS LOCAL_LLM_BASE_URL LOCAL_LLM_MODEL LOCAL_LLM_MODEL_PATH LOCAL_LLM_API_KEY LOCAL_LLM_CANDIDATE_CHARS LOCAL_LLM_TIMEOUT LOCAL_LLM_MAX_CONNECTIONS SEMANTIC_MAX_TOKENS SEMANTIC_MAX_RETRIES SEMANTIC_MAX_EVIDENCE_CHARS SEMANTIC_MAX_CHARS_PER_EVIDENCE REVIEW_MAX_EVIDENCE_CHARS LOCAL_EMBED_MODEL LOCAL_EMBED_DEVICE LOCAL_EMBED_BATCH_SIZE LOCAL_EMBED_WEIGHT LOCAL_EMBED_CHUNK_CHARS LOCAL_EMBED_CHUNK_OVERLAP LOCAL_EMBED_STRICT
}

require_backend_runtime_vars() {
  require_runtime_vars APP_NAME ENVIRONMENT LOG_LEVEL API_PREFIX CORS_ORIGINS DATABASE_URL REDIS_URL STORAGE_ROOT POLICY_RULES_PATH ALGORITHM_ROOT MAX_UPLOAD_BYTES MAX_DOCUMENTS_PER_REVIEW UPLOAD_CHUNK_BYTES BACKEND_HOST BACKEND_PORT BACKEND_API_WORKERS CELERY_WORKER_CONCURRENCY CELERY_WORKER_PREFETCH_MULTIPLIER CELERY_BEAT_SCHEDULE TASK_STALE_AFTER_MINUTES CELERY_REQUEUE_INTERVAL_SECONDS CELERY_STALE_RECOVERY_INTERVAL_SECONDS
}
